from typing import NotRequired,TypedDict
from ...模型后端.llm import 创建用户消息,截上下文摘要

__all__=('模型选择','模型选择引用','安装模型选择')

class 模型选择(TypedDict):
    """一个在线智能体选定的完整提供方、模型与可选推理力度。"""
    provider:str
    model:str
    reasoningEffort:NotRequired[str]

class 模型选择引用(TypedDict):
    """可变模型选择，外加当前步骤捕获的值。"""
    current:object
    assembled:object

def 同一路由(左,右):
    """提供方与模型都相同。"""
    return 左['provider']==右['provider'] and 左['model']==右['model']

def 路由标签(路由,对方):
    """同提供方只写模型，否则写 提供方/模型。"""
    if 路由['provider']==对方['provider']:
        return 路由['model']
    return 路由['provider']+'/'+路由['model']

def 模型切换须知(先前,所选):
    """把提供方/模型切换写成耐久用户角色通知。"""
    自=路由标签(先前,所选)
    至=路由标签(所选,先前)
    return 创建用户消息({
        'content':[{
            'type':'text',
            'text':'[model changed: assistant turns above this point were generated by '+自+'; the session continues with '+至+']',
        }],
        'source':{
            'kind':'model-selection',
            'form':'notice',
            'summary':截上下文摘要(自+' → '+至),
        },
    })

def 安装模型选择(智能体上下文,选择):
    """把一份可变选择接到 Agent 作用域的提示词组装与请求路由。"""
    def 组装监听(_组装,_上下文,下一步):
        """组装时快照所选模型。选择是 dict。"""
        所选=选择['current'] if 'current' in 选择 else None
        组装结果=下一步()
        选择['assembled']=所选
        if 所选 is None:
            return 组装结果
        结果=dict(组装结果)
        变量源=结果['variables'] if 'variables' in 结果 and 结果['variables'] is not None else {}
        变量=dict(变量源)
        变量['provider']=所选['provider']
        变量['model']=所选['model']
        结果['variables']=变量
        return 结果
    拆除组装=智能体上下文.监听('system-prompt/assemble',组装监听)

    def 请求监听(_载体,_载荷,下一步):
        """请求时套用已捕获选择。"""
        已解析=下一步()
        所选=选择['assembled'] if 'assembled' in 选择 else None
        if 所选 is None:
            return 已解析
        去掉=dict(已解析)
        去掉.pop('reasoningEffort',None)
        去掉['provider']=所选['provider']
        去掉['model']=所选['model']
        力度=所选['reasoningEffort'] if 'reasoningEffort' in 所选 else None
        if 力度 is not None:
            去掉['reasoningEffort']=力度
        return 去掉
    拆除请求=智能体上下文.监听('agent/request',请求监听)

    def 须知监听(载荷,下一步):
        """提供方/模型变化时在下一步追加耐久通知。"""
        决定=下一步()
        if 决定['kind']=='reject':
            return 决定
        信号=载荷['signal'] if 'signal' in 载荷 else None
        if 信号 is not None and 信号.is_set():
            return 决定
        消息=决定['messages'] if 'messages' in 决定 else []
        步=载荷['step'] if 'step' in 载荷 else None
        入站=载荷['messages'] if 'messages' in 载荷 else []
        if len(消息)==0 and (步==1 or len(入站)>0):
            return 决定
        所选=选择['assembled'] if 'assembled' in 选择 else None
        智能体=载荷['agent']
        头=智能体.session.请求头()
        先前=None if 头 is None else (头['config'] if 'config' in 头 else None)
        if 所选 is None or 先前 is None or 同一路由(所选,先前):
            return 决定
        结果=dict(决定)
        结果['messages']=list(消息)+[模型切换须知(先前,所选)]
        return 结果
    拆除须知=智能体上下文.监听('agent/pre-step',须知监听,{'前置':True})

    def 拆除():
        """一并拆除三个监听器。"""
        拆除组装()
        拆除请求()
        拆除须知()
    return 拆除
