"""发射器字符串与边界键辅助（与编译器无关）。

对齐上游 `emitter.ts` 纯函数面；实现落在 `发射器`，本模块再导出以兼容既有导入。
"""
from .发射器 import (#再导出
    Typert发射错误,引号,缩进,参数边界键,结果边界键,上下文边界键,调用边界根们,
    quote,indent,invocationBoundaryRoots,安全标识符,safeIdentifier,
)#发射器

def 远程贡献骨架字面量(包名,描述符字面量们):#拼 TYPERT_REMOTE 对象文本
    """descriptors 已是缩进好的对象字面量列表。"""
    行们=[#逐行
        '/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */',
        '',
        'export const TYPERT_REMOTE = {',
        '  package: '+引号(包名)+',',
        '  descriptors: [',
    ]#头
    for 字面 in 描述符字面量们:#每条
        行们.append(缩进(字面,4)+',')#缩进
    行们.append('  ],')#descriptors 止
    行们.append('}')#对象止
    行们.append('')#空行
    行们.append('export default TYPERT_REMOTE')#默认导出
    return '\n'.join(行们)+'\n'#整文件

__all__=[#公开面
    '引号','缩进','参数边界键','结果边界键','上下文边界键','调用边界根们',
    'quote','indent','parameterBoundaryKey','resultBoundaryKey','contextBoundaryKey',
    'invocationBoundaryRoots','Typert发射错误','远程贡献骨架字面量','安全标识符','safeIdentifier',
]#结束

parameterBoundaryKey=参数边界键#上游名
resultBoundaryKey=结果边界键#上游名
contextBoundaryKey=上下文边界键#上游名
