__all__=['中文','英文','侧栏浏览器文案键']#仅中文公开名

中文={#简体中文词典与键集真源
    'type.label':'浏览器',
    'guide.title':'浏览器',
    'guide.description':'浏览 HTTP(S) 网页',
    'address.placeholder':'输入 HTTP(S) 地址',
    'address.changed':'URL 已变化',
    'back':'后退',
    'forward':'前进',
    'reload':'刷新',
    'go':'前往',
    'external':'在系统浏览器中打开',
    'sandbox.disable':'关闭沙箱限制',
    'sandbox.enable':'恢复沙箱限制',
    'sandbox.warning':'沙箱限制已关闭；页面可以导航顶层应用，并使用下载、模态对话框与输入锁定。',
    'start':'输入 HTTP(S) 地址开始浏览',
    'loading':'正在打开…',
    'error.empty':'请输入地址。',
    'error.invalid':'这个地址无效或过长。',
    'error.protocol':'只支持 HTTP 和 HTTPS 地址；本地文件请使用文档预览。',
    'error.credentials':'地址不能包含用户名或密码。',
    'error.application-origin':'不能在嵌入浏览器中打开 DSH 应用自身。',
    'web.loadFailed':'页面报告加载失败或可能禁止嵌入；可尝试在系统浏览器中打开。',
    'web.unknown':'页面已在 iframe 内跳转；Web 模式无法读取当前 URL。',
}#中文结束

侧栏浏览器文案键=tuple(中文.keys())#键联合

英文={#英文词典，对照中文键集
    'type.label':'Browser',
    'guide.title':'Browser',
    'guide.description':'Browse HTTP(S) pages',
    'address.placeholder':'Enter an HTTP(S) address',
    'address.changed':'URL changed',
    'back':'Back',
    'forward':'Forward',
    'reload':'Reload',
    'go':'Go',
    'external':'Open in system browser',
    'sandbox.disable':'Disable sandbox restrictions',
    'sandbox.enable':'Restore sandbox restrictions',
    'sandbox.warning':'Sandbox restrictions are disabled; the page can navigate the top-level app and use downloads, modal dialogs, and input locks.',
    'start':'Enter an HTTP(S) address to start browsing',
    'loading':'Opening…',
    'error.empty':'Enter an address.',
    'error.invalid':'That address is invalid or too long.',
    'error.protocol':'Only HTTP and HTTPS addresses are supported; use Document Preview for local files.',
    'error.credentials':'Addresses cannot contain a username or password.',
    'error.application-origin':'The embedded browser cannot open the DSH application itself.',
    'web.loadFailed':'The page reported a load failure or may block embedding; try opening it in the system browser.',
    'web.unknown':'The page navigated inside the iframe; Web mode cannot read its current URL.',
}#英文结束
