__all__=['模块代理表','模块代理前缀表']

模块代理表={
    #以VFS为后端的真实实现。
    'node:fs':'./node/builtin_modules/implemented/fs.ts',
    'fs':'./node/builtin_modules/implemented/fs.ts',
    'node:fs/promises':'./node/builtin_modules/implemented/fs/promises.ts',
    'fs/promises':'./node/builtin_modules/implemented/fs/promises.ts',
    'node:path':'./node/builtin_modules/implemented/path.ts',
    'path':'./node/builtin_modules/implemented/path.ts',
    'node:path/posix':'./node/builtin_modules/implemented/path.ts',
    'node:os':'./node/builtin_modules/implemented/os.ts',
    'os':'./node/builtin_modules/implemented/os.ts',
    'node:url':'./node/builtin_modules/implemented/url.ts',
    'node:module':'./node/builtin_modules/implemented/module.ts',
    'node:crypto':'./node/builtin_modules/implemented/crypto.ts',
    'crypto':'./node/builtin_modules/implemented/crypto.ts',
    #`buffer`本身保持未别名：shim由该npm包支撑。
    'node:buffer':'./node/builtin_modules/implemented/buffer.ts',
    #隧道请求源：假bind，真路由面。`node:process`与`process`故意缺席——
    #worker宿主安装该全局（`./globals/process.ts`）。
    'node:http':'./node/builtin_modules/implemented/http.ts',
    #同步栈AsyncLocalStorage语义。
    'node:async_hooks':'./node/builtin_modules/implemented/async_hooks.ts',
    #基于浏览器原语的真实实现。
    'node:util':'./node/builtin_modules/implemented/util.ts',
    'node:util/types':'./node/builtin_modules/implemented/util/types.ts',
    'node:events':'./node/builtin_modules/implemented/events.ts',
    'node:timers/promises':'./node/builtin_modules/implemented/timers/promises.ts',
    'node:perf_hooks':'./node/builtin_modules/implemented/perf_hooks.ts',
    'node:tty':'./node/builtin_modules/implemented/tty.ts',
    'tty':'./node/builtin_modules/implemented/tty.ts',
    #真实zstd编解码器：会话日志追加在每次写入时压缩。
    'node:zlib':'./node/builtin_modules/implemented/zlib.ts',
    #worker自己的进程层：`bash -c`与命令表对着VFS跑，
    #因为浏览器worker没有可fork的进程。
    'node:child_process':'./node/builtin_modules/implemented/child_process.ts',
    #结构性mock：每个符号存在，每次调用抛出。
    'node:dns/promises':'./node/builtin_modules/mock/dns/promises.ts',
    'dns/promises':'./node/builtin_modules/mock/dns/promises.ts',
    'node:net':'./node/builtin_modules/mock/net.ts',
    'node:stream':'./node/builtin_modules/implemented/stream.ts',
    'node:vm':'./node/builtin_modules/mock/vm.ts',
    'node:worker_threads':'./node/builtin_modules/mock/worker_threads.ts',
    'node:sqlite':'./node/builtin_modules/mock/sqlite.ts',
    #外部npm替换，以各自所替代的包命名。
    '@deepseek-ai/libreoffice-kit':'./node/external_packages/libreoffice-kit.ts',
    '@deepseek-ai/node-addon-system/flock':'./node/external_packages/node-addon-system-flock.ts',
    'koffi':'./node/external_packages/koffi.ts',
    'sharp':'./node/external_packages/sharp.ts',
    'node-pty':'./node/external_packages/node-pty.ts',
    'execa':'./node/external_packages/execa.ts',
    '@vscode/ripgrep':'./node/external_packages/ripgrep.ts',
    '@earendil-works/pi-ai':'./node/external_packages/pi-ai.ts',
    #可构造的假对象，其方法从不被触及。
    'ws':'./node/external_packages/ws.ts',
}

模块代理前缀表={
    '@earendil-works/pi-ai/':'./node/external_packages/pi-ai.ts',
}
