import json,os,re#字面量、路径与标识符
from .渲染器 import 类型图渲染器#类型图渲染器

__all__=[#公开面
    'Typert代码输出错误','面模型代码输出器',
    '引号','缩进','安全标识符','参数边界键','结果边界键','上下文边界键','边界根列表',
    '远程贡献骨架字面量',
]#结束

class Typert代码输出错误(Exception):#代码输出期失败
    """把已建模构造投影成制品失败。"""
    name='TypertEmitError'#错误名

def 引号(值):#单引号 JS 字符串字面量
    """转义反斜杠、引号、换行。"""
    return "'"+str(值).replace('\\','\\\\').replace("'","\\'").replace('\n','\\n').replace('\r','\\r')+"'"#字面量

def 缩进(文本,空格数):#给多行文本每行加前缀空格
    """逐行加前缀。"""
    前缀=' '*空格数#前缀
    return '\n'.join(前缀+行 for 行 in 文本.split('\n'))#拼回

def 远程贡献骨架字面量(包名,描述符字面量列表):#拼 TYPERT_REMOTE 对象文本
    """descriptors 已是缩进好的对象字面量列表。"""
    行列表=[#逐行
        '/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */',
        '',
        'export const TYPERT_REMOTE = {',
        '  package: '+引号(包名)+',',
        '  descriptors: [',
    ]#头
    for 描述符字面量 in 描述符字面量列表:#每条
        行列表.append(缩进(描述符字面量,4)+',')#缩进
    行列表.append('  ],')#descriptors 止
    行列表.append('}')#对象止
    行列表.append('')#空行
    行列表.append('export default TYPERT_REMOTE')#默认导出
    return '\n'.join(行列表)+'\n'#整文件

def 安全标识符(名):#任意名 → 合法标识符
    """非法字符换成下划线。"""
    归一=re.sub(r'[^$\w]','_',名)#非法换下划线
    if re.match(r'^[$A-Z_a-z]',归一):#已有合法起首
        return 归一#原样
    return '_'+归一#前缀下划线

def 参数边界键(调用,序号):#参数边界键
    """id 加参数下标。"""
    return (调用['id'] if 调用 is not None and 'id' in 调用 else None)+':parameter:'+str(序号)#键

def 结果边界键(调用):#结果边界键
    """id 加 result。"""
    return (调用['id'] if 调用 is not None and 'id' in 调用 else None)+':result'#键

def 上下文边界键(调用):#身份边界键
    """id 加 context。"""
    return (调用['id'] if 调用 is not None and 'id' in 调用 else None)+':context'#键

def 边界根列表(调用列表):#调用列表上的全部边界根
    """供模式代码输出器只为调用边界输出模式。"""
    结果=[]#收集根
    for 调用 in 调用列表 or []:#逐条调用
        约定=(调用['invocation'] if 调用 is not None and 'invocation' in 调用 else None) or {}#调用约定
        if (约定['kind'] if 约定 is not None and 'kind' in 约定 else None)=='context':#context 调用有身份边界
            边界=(约定['boundary'] if 约定 is not None and 'boundary' in 约定 else None) or {}#身份边界
            结果.append({'key':上下文边界键(调用),'type':边界['codecType'] if 边界 is not None and 'codecType' in 边界 else None})#身份编解码类型
        for 序号,参数 in enumerate((调用['parameters'] if 调用 is not None and 'parameters' in 调用 else None) or []):#每个业务参数
            边界=(参数['boundary'] if 参数 is not None and 'boundary' in 参数 else None) or {}#参数边界
            结果.append({'key':参数边界键(调用,序号),'type':边界['codecType'] if 边界 is not None and 'codecType' in 边界 else None})#参数编解码
        结果边界=(调用['result'] if 调用 is not None and 'result' in 调用 else None) or {}#结果边界
        结果.append({'key':结果边界键(调用),'type':结果边界['codecType'] if 结果边界 is not None and 'codecType' in 结果边界 else None})#结果编解码
    return 结果#全部边界根

def 文档字面量(文档):#文档字段的可 JSON 字面量
    """省略未定义的可选字段。"""
    出={}#结果
    描述=文档['description'] if 文档 is not None and 'description' in 文档 else None#描述
    if 描述 is not None:#有描述
        出['description']=描述#描述
    摘要=文档['summary'] if 文档 is not None and 'summary' in 文档 else None#摘要
    if 摘要 is not None:#有摘要
        出['summary']=摘要#摘要
    出['tags']=list((文档['tags'] if 文档 is not None and 'tags' in 文档 else None) or [])#标签始终写入
    原始文档=文档['jsDoc'] if 文档 is not None and 'jsDoc' in 文档 else None#原始 JSDoc
    if 原始文档 is not None:#有原始 JSDoc
        出['jsDoc']=原始文档#JSDoc
    return 出#字面量

def 严格编解码字面量(边界,模式名):#严格模式编解码字面量
    """mode/typeSymbol/create。"""
    return '\n'.join([#逐行
        '{',
        "  mode: 'strict',",
        '  typeSymbol: '+引号(边界['typeSymbol'] if 边界 is not None and 'typeSymbol' in 边界 else None)+',',
        '  create: '+模式名+',',
        '}',
    ])#拼成多行

def 包导出说明符(包名,子路径):#包名加导出示路径 → 模块说明符
    """`.` 即包根。"""
    return 包名 if 子路径=='.' else 包名+子路径[1:]#拼子路径

def 渲染远程属性名(名):#方法名 → 接口属性名
    """合法标识符裸写，否则加引号。"""
    return 名 if re.match(r'^[$A-Z_a-z][$\w]*$',名) else 引号(名)#属性名

def 去重命名空间(调用列表):#调用列表中的去重命名空间
    """去重后排序。"""
    return sorted({(调用['namespace'] if 调用 is not None and 'namespace' in 调用 else None) for 调用 in 调用列表})#集合排序

def 远程命名空间接口(命名空间):#命名空间 → 稳定接口名
    """用 utf8 十六进制避免非法标识符。"""
    return 'TypertRemoteNamespace$'+命名空间.encode('utf-8').hex()#十六进制

def 远程声明源(包模型,调用):#Remote 声明 map 的源路径
    """相对包根；声明在 lib/，源在包内再上一层。"""
    根=(包模型['root'] if 包模型 is not None and 'root' in 包模型 else None) or ''#包根
    位置=调用['location'] if 调用 is not None and 'location' in 调用 else None#位置
    文件=(位置['file'] if 位置 is not None and 'file' in 位置 else None) or ''#源文件
    相对=os.path.relpath(文件,根).replace('\\','/')#相对包根
    if 相对=='' or 相对=='..' or 相对.startswith('../') or os.path.isabs(相对):#逃出包根
        raise Typert代码输出错误('Remote declaration '+str(调用['id'] if 调用 is not None and 'id' in 调用 else None)+' is outside its package root '+根)#越界
    return '../'+相对#声明在 lib/

def 收集远程导入(调用列表):#调用边界上的公开类型导入
    """按符号去重。"""
    导入表={}#符号 → 导入
    def 并入(边界):#把一条边界的导入并入
        """把一条边界的导入并入。"""
        for 项 in (边界['imports'] if 边界 is not None and 'imports' in 边界 else None) or []:#逐条公开导入
            符号=项['symbol'] if 项 is not None and 'symbol' in 项 else None#符号
            当前=导入表[符号] if 符号 in 导入表 else None#同符号已有
            当前说明符=当前['specifier'] if 当前 is not None and 'specifier' in 当前 else None#已有说明符
            项说明符=项['specifier'] if 项 is not None and 'specifier' in 项 else None#新说明符
            当前名=当前['name'] if 当前 is not None and 'name' in 当前 else None#已有名
            项名=项['name'] if 项 is not None and 'name' in 项 else None#新名
            if 当前 is not None and (当前说明符!=项说明符 or 当前名!=项名):#冲突
                raise Typert代码输出错误('typert Remote emitter: symbol '+str(符号)+' has inconsistent public imports')#冲突
            导入表[符号]=项#记下
    for 调用 in 调用列表 or []:#逐条调用
        约定=(调用['invocation'] if 调用 is not None and 'invocation' in 调用 else None) or {}#约定
        if (约定['kind'] if 约定 is not None and 'kind' in 约定 else None)=='context':#身份
            并入((约定['boundary'] if 约定 is not None and 'boundary' in 约定 else None) or {})#身份边界
        for 参数 in (调用['parameters'] if 调用 is not None and 'parameters' in 调用 else None) or []:#参数
            并入((参数['boundary'] if 参数 is not None and 'boundary' in 参数 else None) or {})#参数边界
        并入((调用['result'] if 调用 is not None and 'result' in 调用 else None) or {})#结果边界
    def 导入排序键(项):#按说明符与导出名排序
        """按说明符与导出名排序。"""
        说明符=项['specifier'] if 项 is not None and 'specifier' in 项 else None#说明符
        名=项['name'] if 项 is not None and 'name' in 项 else None#导出名
        return (说明符,名)#键
    return sorted(导入表.values(),key=导入排序键)#排序

def 分配远程导入名(导入列表):#为 Remote 导入分配不冲突本地名
    """避开协议名与贡献常量。"""
    已用={'TypertRemoteContribution','TYPERT_REMOTE'}#已占用
    名表={}#符号 → 本地名
    for 项 in 导入列表:#逐条
        基=安全标识符((项['name'] if 项 is not None and 'name' in 项 else None) or 'T')#基底
        名=基#候选
        后缀=2#冲突从 2
        while 名 in 已用:#冲突
            名=基+'$remote'+str(后缀)#加后缀
            后缀+=1#递增
        已用.add(名)#占用
        名表[项['symbol'] if 项 is not None and 'symbol' in 项 else None]=名#记下
    return 名表#映射

class 模式代码输出器:#Zod 模式代码输出器
    """把选定声明与调用边界投影成 Zod 源码。"""
    def __init__(自身,渲染器,模式列表,边界列表):#按模式与边界根收集闭包并分配内部名
        """构造期分配唯一 $schema 名。"""
        自身.渲染器=渲染器#类型图渲染器
        自身.模式列表=list(模式列表 or [])#显式选定的模式
        自身.边界列表=list(边界列表 or [])#调用边界根
        自身.名表={}#声明符号 → 内部模式名
        自身.边界名表={}#边界键 → 内部模式名
        声明图={}#闭包去重
        for 模式 in 自身.模式列表:#每个显式模式
            for 声明 in 渲染器.收集类型声明闭包([模式['type'] if 模式 is not None and 'type' in 模式 else None]):#其类型闭包
                声明图[声明['id'] if 声明 is not None and 'id' in 声明 else None]=声明#按 id 去重
        for 边界 in 自身.边界列表:#每条调用边界
            类型=边界['type'] if 边界 is not None and 'type' in 边界 else None#编解码类型
            if 类型 is None:#缺类型
                continue#跳过
            for 声明 in 渲染器.收集类型声明闭包([类型]):#其编解码类型闭包
                声明图[声明['id'] if 声明 is not None and 'id' in 声明 else None]=声明#按 id 去重
        图声明列表=(渲染器.graph['declarations'] if 渲染器.graph is not None and 'declarations' in 渲染器.graph else None) or []#图序
        自身.声明列表=[声明 for 声明 in 图声明列表 if (声明['id'] if 声明 is not None and 'id' in 声明 else None) in 声明图]#保持图序
        已占用名集合=set()#已占用的内部名
        for 声明 in 自身.声明列表:#为每个声明分配模式名
            基=安全标识符((声明['name'] if 声明 is not None and 'name' in 声明 else None) or 'T')+'$schema'#名加 $schema
            名=基#候选
            后缀=2#冲突从 2
            while 名 in 已占用名集合:#冲突
                名=基+str(后缀)#加数字
                后缀+=1#递增
            已占用名集合.add(名)#占用
            自身.名表[声明['id'] if 声明 is not None and 'id' in 声明 else None]=名#记下
        for 边界 in 自身.边界列表:#为每条边界分配模式名
            基=安全标识符((边界['key'] if 边界 is not None and 'key' in 边界 else None) or 'b')+'$schema'#键加 $schema
            名=基#候选
            后缀=2#冲突从 2
            while 名 in 已占用名集合:#冲突
                名=基+str(后缀)#加数字
                后缀+=1#递增
            已占用名集合.add(名)#占用
            自身.边界名表[边界['key'] if 边界 is not None and 'key' in 边界 else None]=名#记下

    def 输出代码(自身):#输出定义行、导出与边界查询
        """组装模式制品。"""
        定义列表=[自身.声明定义(声明) for 声明 in 自身.声明列表]#声明 → 惰性工厂
        for 边界 in 自身.边界列表:#每条边界再补一条惰性工厂
            名=自身.边界名(边界['key'] if 边界 is not None and 'key' in 边界 else None)#内部名
            定义列表.append('let '+名+'$value\nconst '+名+' = () => ('+名+'$value ??= '+自身.类型模式(边界['type'] if 边界 is not None and 'type' in 边界 else None)+')')#边界工厂
        导出列表=[]#导出表
        for 模型 in 自身.模式列表:#显式模式
            导出=模型['export'] if 模型 is not None and 'export' in 模型 else None#导出
            导出列表.append({#一条导出
                'model':模型,#源模型
                'exportName':安全标识符((导出['name'] if 导出 is not None and 'name' in 导出 else None) or 'schema'),#安全导出名
                'internalName':自身.导出模式名(模型),#内部模式名
            })#结束
        return {#组装
            'definitions':定义列表,#定义行
            'exports':导出列表,#导出表
            'boundary':自身.边界名,#按键取内部名
        }#制品

    def 声明定义(自身,声明):#一条声明的 const 定义
        """非泛型直接值；泛型工厂。"""
        名=自身.模式名(声明['id'] if 声明 is not None and 'id' in 声明 else None)#内部名
        类型参数=(声明['typeParameters'] if 声明 is not None and 'typeParameters' in 声明 else None) or []#类型参数
        if len(类型参数)==0:#非泛型
            return 'let '+名+'$value\nconst '+名+' = () => ('+名+'$value ??= '+自身.声明模式(声明,{})+')'#惰性工厂
        形参列表=[]#形参名与 id
        for 序号,参数 in enumerate(类型参数):#逐个
            形参列表.append(('type'+str(序号)+'$schema',参数['id'] if 参数 is not None and 'id' in 参数 else None))#形参
        替换={标识:形参 for 形参,标识 in 形参列表}#id → 形参名
        return 'const '+名+' = ('+', '.join(形参 for 形参,_ in 形参列表)+') => '+自身.声明模式(声明,替换)#工厂

    def 声明模式(自身,声明,替换):#声明本身的 Zod 表达式
        """按种类投影。"""
        种类=声明['kind'] if 声明 is not None and 'kind' in 声明 else None#种类
        if 种类=='enum':#枚举无 JSON 投影
            自身.失败(声明['name'] if 声明 is not None and 'name' in 声明 else None,'enum declarations have no Zod projection')#拒绝
        if 种类=='alias':#类型别名
            别名类型=声明['type'] if 声明 is not None and 'type' in 声明 else None#别名目标
            if 别名类型 is None:#缺类型
                自身.失败(声明['name'] if 声明 is not None and 'name' in 声明 else None,'alias has no modeled type')#失败
            return 自身.描述(自身.类型模式(别名类型,替换),声明)#投影并挂描述
        自身对象=自身.对象模式((声明['members'] if 声明 is not None and 'members' in 声明 else None) or [],声明['name'] if 声明 is not None and 'name' in 声明 else None,替换)#自身成员
        结果=自身对象#从自身出发
        for 基 in (声明['extends'] if 声明 is not None and 'extends' in 声明 else None) or []:#逐个 extends
            结果='z.intersection('+自身.类型模式(基,替换)+', '+结果+')'#与基相交
        return 自身.描述(结果,声明)#挂 JSDoc

    def 类型模式(自身,标识,替换=None):#类型节点 → Zod 表达式
        """按节点种类投影。"""
        if 替换 is None:#缺省
            替换={}#空
        节点=自身.渲染器.node(标识)#取节点
        种类=节点['kind'] if 节点 is not None and 'kind' in 节点 else None#种类
        if 种类=='keyword':#关键字
            return 自身.关键字模式(节点['name'] if 节点 is not None and 'name' in 节点 else None)#关键字
        if 种类=='literal':#字面量
            return 'z.literal('+(节点['text'] if 节点 is not None and 'text' in 节点 else None)+')'#字面量
        if 种类=='parenthesized':#括号
            return 自身.类型模式(节点['type'] if 节点 is not None and 'type' in 节点 else None,替换)#剥一层
        if 种类=='reference':#引用
            return 自身.引用模式(节点,替换)#引用
        if 种类=='union':#联合
            类型列表=(节点['types'] if 节点 is not None and 'types' in 节点 else None) or []#成员
            if len(类型列表)==0:#空
                return 'z.never()'#永不
            if len(类型列表)==1:#单元素
                return 自身.类型模式(类型列表[0],替换)#直接
            return 'z.union(['+', '.join(自身.类型模式(项,替换) for 项 in 类型列表)+'])'#联合
        if 种类=='intersection':#交叉
            类型列表=(节点['types'] if 节点 is not None and 'types' in 节点 else None) or []#成员
            if len(类型列表)==0:#空
                return 'z.unknown()'#unknown
            结果=自身.类型模式(类型列表[0],替换)#头部
            for 右 in 类型列表[1:]:#其余
                结果='z.intersection('+结果+', '+自身.类型模式(右,替换)+')'#相交
            return 结果#交叉
        if 种类=='array':#数组
            return 'z.array('+自身.类型模式(节点['element'] if 节点 is not None and 'element' in 节点 else None,替换)+')'#数组
        if 种类=='tuple':#元组
            元素列表=(节点['elements'] if 节点 is not None and 'elements' in 节点 else None) or []#元素
            固定=[元素 for 元素 in 元素列表 if not (元素['rest'] if 元素 is not None and 'rest' in 元素 else None)]#固定段
            剩余元素=None#rest 元素
            for 元素 in 元素列表:#找 rest
                if 元素['rest'] if 元素 is not None and 'rest' in 元素 else None:#rest
                    剩余元素=元素#记下
                    break#只取第一个
            模式='z.tuple(['+', '.join(自身.可选(自身.类型模式(元素['type'] if 元素 is not None and 'type' in 元素 else None,替换),元素['optional'] if 元素 is not None and 'optional' in 元素 else None) for 元素 in 固定)+'])'#固定
            if 剩余元素 is not None:#有 rest
                模式+='.rest('+自身.元组剩余模式(剩余元素['type'] if 剩余元素 is not None and 'type' in 剩余元素 else None,替换)+')'#追加
            return 模式#元组
        if 种类=='object':#匿名对象
            return 自身.对象模式((节点['members'] if 节点 is not None and 'members' in 节点 else None) or [],标识,替换)#对象
        自身.失败(节点['id'] if 节点 is not None and 'id' in 节点 else None,'type node '+str(种类)+' has no Zod projection')#无投影

    def 引用模式(自身,节点,替换):#引用节点 → Zod
        """声明 / 类型参数 / 标准库。"""
        目标=(节点['target'] if 节点 is not None and 'target' in 节点 else None) or {}#目标
        目标种类=目标['kind'] if 目标 is not None and 'kind' in 目标 else None#目标种类
        节点名=节点['name'] if 节点 is not None and 'name' in 节点 else None#节点名
        if 目标种类=='declaration':#指向声明
            符号=目标['symbol'] if 目标 is not None and 'symbol' in 目标 else None#声明符号
            名=自身.模式名(符号)#内部名
            声明=自身.渲染器.declaration(符号)#声明
            实参=(节点['arguments'] if 节点 is not None and 'arguments' in 节点 else None) or []#类型实参
            if len((声明['typeParameters'] if 声明 is not None and 'typeParameters' in 声明 else None) or [])==0:#非泛型
                if len(实参)>0:#多余实参
                    自身.失败(节点名,'non-generic declaration received '+str(len(实参))+' type arguments')#失败
                return 'z.lazy(() => '+名+'())'#惰性调用工厂
            参数模式=自身.声明实参(节点,声明,替换)#解析实参
            return 'z.lazy(() => '+名+'('+', '.join(参数模式)+'))'#调用工厂
        if 目标种类=='type-parameter':#类型参数
            if len((节点['arguments'] if 节点 is not None and 'arguments' in 节点 else None) or [])>0:#不能实例化
                自身.失败(节点名,'type parameter reference cannot receive type arguments')#失败
            参数标识=目标['parameter'] if 目标 is not None and 'parameter' in 目标 else None#形参 id
            模式=替换[参数标识] if 参数标识 is not None and 参数标识 in 替换 else None#查找替换
            if 模式 is None:#闭包外
                自身.失败(节点名,'type parameter has no schema substitution')#失败
            return 模式#形参名
        if 目标种类=='standard':#标准库
            标准名=目标['name'] if 目标 is not None and 'name' in 目标 else None#标准名
            实参=(节点['arguments'] if 节点 is not None and 'arguments' in 节点 else None) or []#实参
            if 标准名 in ('Array','ReadonlyArray'):#数组
                if len(实参)==0:#缺元素
                    自身.失败(节点名,'array reference has no element type')#失败
                数组='z.array('+自身.类型模式(实参[0],替换)+')'#元素数组
                return 数组+('.readonly()' if 标准名=='ReadonlyArray' else '')#只读
            if 标准名=='Record':#记录
                if len(实参)<2:#必须两个
                    自身.失败(节点名,'Record requires key and value types')#失败
                return 'z.record('+自身.类型模式(实参[0],替换)+', '+自身.类型模式(实参[1],替换)+')'#记录
            if 标准名=='Date':#日期
                return 'z.date()'#日期
            自身.失败(节点名,'standard type '+str(标准名)+' has no Zod projection')#拒绝
        自身.失败(节点名,str(目标种类)+' reference has no Zod projection')#其余拒绝

    def 声明实参(自身,节点,声明,替换):#解析泛型声明的类型实参
        """每个形参对应的 Zod 表达式。"""
        实参=(节点['arguments'] if 节点 is not None and 'arguments' in 节点 else None) or []#实参
        形参=(声明['typeParameters'] if 声明 is not None and 'typeParameters' in 声明 else None) or []#形参
        节点名=节点['name'] if 节点 is not None and 'name' in 节点 else None#节点名
        if len(实参)>len(形参):#过多
            自身.失败(节点名,'generic declaration accepts '+str(len(形参))+' type arguments but received '+str(len(实参)))#失败
        已解析=dict(替换)#后续默认能看见先解析的
        结果=[]#按形参序
        for 序号,参数 in enumerate(形参):#逐个
            if 序号<len(实参):#显式实参
                模式=自身.类型模式(实参[序号],替换)#外层替换
            elif (参数['default'] if 参数 is not None and 'default' in 参数 else None) is not None:#用默认
                模式=自身.类型模式(参数['default'] if 参数 is not None and 'default' in 参数 else None,已解析)#看见已解析
            else:#缺实参且无默认
                自身.失败(节点名,'missing type argument '+str(参数['name'] if 参数 is not None and 'name' in 参数 else None))#失败
            结果.append(模式)#收下
            已解析[参数['id'] if 参数 is not None and 'id' in 参数 else None]=模式#供后续默认
        return 结果#列表

    def 元组剩余模式(自身,标识,替换):#元组 rest 必须是数组类型
        """T[] 或 Array/ReadonlyArray。"""
        节点=自身.渲染器.node(标识)#取节点
        种类=节点['kind'] if 节点 is not None and 'kind' in 节点 else None#种类
        if 种类=='array':#T[]
            return 自身.类型模式(节点['element'] if 节点 is not None and 'element' in 节点 else None,替换)#元素
        if 种类=='reference':#标准数组引用
            目标=(节点['target'] if 节点 is not None and 'target' in 节点 else None) or {}#目标
            if (目标['kind'] if 目标 is not None and 'kind' in 目标 else None)=='standard' and (目标['name'] if 目标 is not None and 'name' in 目标 else None) in ('Array','ReadonlyArray'):#数组
                实参=(节点['arguments'] if 节点 is not None and 'arguments' in 节点 else None) or []#实参
                if len(实参)==0:#缺
                    自身.失败(节点['name'] if 节点 is not None and 'name' in 节点 else None,'tuple rest array has no element type')#失败
                return 自身.类型模式(实参[0],替换)#元素
        自身.失败(标识,'tuple rest element must retain an array type')#拒绝

    def 对象模式(自身,成员列表,主体,替换):#成员列表 → z.object / z.record
        """固定属性与索引签名。"""
        属性列表=[]#固定 JSON 属性
        索引列表=[]#索引签名
        符号成员=0#唯一符号成员计数
        for 成员 in 成员列表:#逐个成员
            成员名=成员['name'] if 成员 is not None and 'name' in 成员 else None#成员名
            成员种类=成员['kind'] if 成员 is not None and 'kind' in 成员 else None#种类
            if (成员['static'] if 成员 is not None and 'static' in 成员 else None) or (成员['visibility'] if 成员 is not None and 'visibility' in 成员 else None)!='public':#静态或非公开
                continue#跳过
            if (成员['computed'] if 成员 is not None and 'computed' in 成员 else None)=='symbol':#唯一符号键
                符号成员+=1#计入
                continue#无 JSON 名
            if (成员['computed'] if 成员 is not None and 'computed' in 成员 else None)=='dynamic':#动态计算名
                自身.失败(主体,'computed member '+str(成员名)+' has no fixed JSON property name')#失败
            if 成员种类=='index':#索引签名
                签名=成员['signature'] if 成员 is not None and 'signature' in 成员 else None#签名
                参数列表=(签名['parameters'] if 签名 is not None and 'parameters' in 签名 else None) or []#键参数
                if len(参数列表)!=1:#必须恰好一个
                    自身.失败(主体,'index signature must have exactly one key parameter')#失败
                记录='z.record('+自身.类型模式(参数列表[0]['type'] if 参数列表[0] is not None and 'type' in 参数列表[0] else None,替换)+', '+自身.类型模式(签名['returns'] if 签名 is not None and 'returns' in 签名 else None,替换)+')'#键值
                if 成员['readonly'] if 成员 is not None and 'readonly' in 成员 else None:#只读
                    记录+='.readonly()'#readonly
                索引列表.append(记录)#记下
                continue#不进 properties
            if 成员种类!='property':#方法等不可投影
                自身.失败(主体,str(成员种类)+' member '+str(成员名)+' is not data-schema projectable')#失败
            属性模式=自身.描述(#属性模式
                自身.可选(自身.只读(自身.类型模式(成员['type'] if 成员 is not None and 'type' in 成员 else None,替换),成员['readonly'] if 成员 is not None and 'readonly' in 成员 else None),成员['optional'] if 成员 is not None and 'optional' in 成员 else None),
                成员,#挂成员文档
            )#结束
            JSON名=成员['jsonName'] if 成员 is not None and 'jsonName' in 成员 else None#JSON 名
            属性名=JSON名 if JSON名 is not None else 成员名#JSON 名优先
            属性列表.append(引号(属性名)+': '+属性模式)#属性行
        if len(索引列表)>1:#多于一个索引
            自身.失败(主体,'object type has more than one JSON index signature')#拒绝
        if len(属性列表)==0 and len(索引列表)==0 and 符号成员>0:#纯符号对象
            return 'z.unknown()'#unknown
        对象体='' if len(属性列表)==0 else '\n'+'\n'.join('  '+项+',' for 项 in 属性列表)+'\n'#属性体
        对象='z.object({'+对象体+'})'#固定属性对象
        if len(索引列表)==0:#无索引
            return 对象#只返回对象
        if len(属性列表)==0:#无属性
            return 索引列表[0]#只返回记录
        return 'z.intersection('+对象+', '+索引列表[0]+')'#对象与索引相交

    def 导出模式名(自身,模型):#显式模式导出对应的内部名
        """泛型不能直接当导出值。"""
        符号=模型['symbol'] if 模型 is not None and 'symbol' in 模型 else None#声明符号
        名=自身.模式名(符号)#内部名
        声明=自身.渲染器.declaration(符号)#声明
        if len((声明['typeParameters'] if 声明 is not None and 'typeParameters' in 声明 else None) or [])>0:#泛型
            导出=模型['export'] if 模型 is not None and 'export' in 模型 else None#导出
            自身.失败(导出['name'] if 导出 is not None and 'name' in 导出 else None,'generic schema exports require a concrete declaration')#失败
        return 名#内部名

    def 关键字模式(自身,名):#关键字类型 → Zod
        """按关键字名。"""
        表={#关键字 → Zod
            'any':'z.any()','unknown':'z.unknown()','never':'z.never()',
            'string':'z.string()','number':'z.number()','bigint':'z.bigint()',
            'boolean':'z.boolean()','symbol':'z.symbol()','undefined':'z.undefined()',
            'void':'z.void()',
            'object':"z.custom((value) => (typeof value === 'object' && value !== null) || typeof value === 'function')",
        }#表
        if 名 not in 表:#其余拒绝
            自身.失败(名,'keyword '+str(名)+' has no Zod projection')#失败
        return 表[名]#Zod

    def 模式名(自身,符号):#声明符号 → 内部模式名
        """闭包外声明则失败。"""
        名=自身.名表[符号] if 符号 in 自身.名表 else None#查找
        if 名 is None:#闭包外
            自身.失败(符号,'referenced declaration is outside the selected schema closure')#失败
        return 名#内部名

    def 边界名(自身,键):#边界键 → 内部模式名
        """未收录则失败。"""
        名=自身.边界名表[键] if 键 in 自身.边界名表 else None#查找
        if 名 is None:#未收录
            自身.失败(键,'invocation boundary is outside the selected schema roots')#失败
        return 名#内部名

    def 描述(自身,模式,文档):#有描述则 .describe()
        """无描述原样返回。"""
        说明=文档['description'] if 文档 is not None and 'description' in 文档 else None#描述
        return 模式 if 说明 is None else 模式+'.describe('+引号(说明)+')'#挂描述

    def 可选(自身,模式,是否可选):#可选则 .optional()
        """非可选原样。"""
        return 模式+'.optional()' if 是否可选 else 模式#可选

    def 只读(自身,模式,是否只读):#只读则 .readonly()
        """非只读原样。"""
        return 模式+'.readonly()' if 是否只读 else 模式#只读

    def 失败(自身,主体,消息):#统一抛出代码输出错误
        """主体加说明。"""
        raise Typert代码输出错误('typert Zod emitter: '+str(主体)+': '+消息)#抛出

class 面模型代码输出器:#面模型代码输出器
    """从一份独立分析过的面输出生成的运行时与类型制品。"""
    def __init__(自身,面):#按一面图构造
        """用该面类型图构造渲染器。"""
        自身.面=面#面模型
        自身.渲染器=类型图渲染器(面['graph'] if 面 is not None and 'graph' in 面 else None)#渲染器

    def 输出代码(自身,包名):#输出一个包的制品
        """可执行 JavaScript 及其精确声明；宿主面且有调用则带 Remote。"""
        包模型=None#命中包
        for 候选 in (自身.面['packages'] if 自身.面 is not None and 'packages' in 自身.面 else None) or []:#按名找
            if (候选['name'] if 候选 is not None and 'name' in 候选 else None)==包名:#命中
                包模型=候选#记下
                break#停止
        面名=自身.面['face'] if 自身.面 is not None and 'face' in 自身.面 else None#面名
        if 包模型 is None:#本面没有该包
            raise Typert代码输出错误('typert emitter('+str(面名)+'): package '+包名+' is not modeled on this face')#失败
        调用列表=(包模型['invocations'] if 包模型 is not None and 'invocations' in 包模型 else None) or []#调用
        模式列表=(包模型['schemas'] if 包模型 is not None and 'schemas' in 包模型 else None) or []#显式模式
        模式制品=模式代码输出器(#为本包构造模式代码输出器
            自身.渲染器,#渲染器
            模式列表,#显式模式
            边界根列表(调用列表),#调用边界根
        ).输出代码()#立刻输出
        运行时=自身.运行时模型(包模型)#抽出运行时快照
        导出名列表=[]#模式导出名
        for 模式 in 模式列表:#逐条
            导出=模式['export'] if 模式 is not None and 'export' in 模式 else None#导出
            导出名列表.append(导出['name'] if 导出 is not None and 'name' in 导出 else None)#记下
        结果={#组装本包代码输出结果
            'package':包名,#包名
            'face':面名,#所在面
            'exports':导出名列表,#模式导出名
            'js':自身.渲染Js(包模型,模式制品,运行时),#可执行 JS
            'dts':自身.渲染Dts(包模型,模式制品),#精确声明
        }#结束
        if 面名=='host' and len(调用列表)>0:#宿主面且有调用
            结果['remote']=自身.输出远程(包模型)#Host-for-Client Remote
        return 结果#代码输出结果

    def 运行时模型(自身,包模型):#抽出 TYPERT.model 快照
        """服务 / 事件 / 对象。"""
        服务列表=[]#服务列表
        面名=自身.面['face'] if 自身.面 is not None and 'face' in 自身.面 else None#面名
        for 服务 in (包模型['services'] if 包模型 is not None and 'services' in 包模型 else None) or []:#逐条服务
            成员标识列表=(服务['members'] if 服务 is not None and 'members' in 服务 else None) or []#成员 id
            成员列表=[自身.运行时成员(自身.渲染器.member(标识)) for 标识 in 成员标识列表]#投影成员
            条目=文档字面量(服务)#文档
            条目['key']=服务['key'] if 服务 is not None and 'key' in 服务 else None#服务键
            导出=服务['export'] if 服务 is not None and 'export' in 服务 else None#导出
            条目['exportName']=导出['name'] if 导出 is not None and 'name' in 导出 else None#导出名
            条目['members']=成员列表#成员
            条目['types']=自身.运行时类型(自身.渲染器.收集成员声明闭包(成员标识列表),服务['symbol'] if 服务 is not None and 'symbol' in 服务 else None)#附属类型
            服务列表.append(条目)#收下
        事件列表=[]#事件列表
        for 事件 in (包模型['events'] if 包模型 is not None and 'events' in 包模型 else None) or []:#逐条事件
            节点=自身.渲染器.node(事件['signature'] if 事件 is not None and 'signature' in 事件 else None)#签名节点
            if (节点['kind'] if 节点 is not None and 'kind' in 节点 else None)!='function':#必须是函数
                raise Typert代码输出错误('typert emitter('+str(面名)+'): event '+str(事件['name'] if 事件 is not None and 'name' in 事件 else None)+' is not a function type')#失败
            条目=文档字面量(事件)#文档
            事件名=事件['name'] if 事件 is not None and 'name' in 事件 else None#事件名
            条目['name']=事件名#事件名
            模式=事件['mode'] if 事件 is not None and 'mode' in 事件 else None#模式
            if 模式 is not None:#有模式
                条目['mode']=模式#模式
            条目['signature']=引号(事件名)+自身.渲染器.renderSignature(节点['signature'] if 节点 is not None and 'signature' in 节点 else None)#名加签名
            事件列表.append(条目)#收下
        对象列表=[]#对象列表
        for 对象 in (包模型['objects'] if 包模型 is not None and 'objects' in 包模型 else None) or []:#逐条对象
            声明=自身.渲染器.declaration(对象['symbol'] if 对象 is not None and 'symbol' in 对象 else None)#对象声明
            条目=文档字面量(对象)#文档
            条目['name']=声明['name'] if 声明 is not None and 'name' in 声明 else None#声明名
            导出=对象['export'] if 对象 is not None and 'export' in 对象 else None#导出
            条目['exportName']=导出['name'] if 导出 is not None and 'export' in 导出 else None#导出名
            声明成员=(声明['members'] if 声明 is not None and 'members' in 声明 else None) or []#成员
            条目['members']=[自身.运行时成员(成员) for 成员 in 声明成员]#投影成员
            条目['types']=自身.运行时类型(自身.渲染器.收集成员声明闭包([成员['id'] if 成员 is not None and 'id' in 成员 else None for 成员 in 声明成员]),声明['id'] if 声明 is not None and 'id' in 声明 else None)#附属
            对象列表.append(条目)#收下
        return {'services':服务列表,'events':事件列表,'objects':对象列表}#包级快照

    def 运行时成员(自身,成员):#投影一条运行时成员
        """成员快照。"""
        条目={#成员
            'kind':成员['kind'] if 成员 is not None and 'kind' in 成员 else None,#种类
            'name':成员['name'] if 成员 is not None and 'name' in 成员 else None,#名
            'signature':自身.渲染器.renderMember(成员,True),#渲染签名
        }#结束
        摘要=成员['summary'] if 成员 is not None and 'summary' in 成员 else None#摘要
        if 摘要 is not None:#有摘要
            条目['summary']=摘要#摘要
        原始文档=成员['jsDoc'] if 成员 is not None and 'jsDoc' in 成员 else None#JSDoc
        if 原始文档 is not None:#有 JSDoc
            条目['jsDoc']=原始文档#JSDoc
        return 条目#快照

    def 运行时类型(自身,声明列表,根):#闭包中去掉根后的附属类型
        """名称与声明文本，按名排序。"""
        结果=[]#列表
        for 声明 in 声明列表:#从闭包
            标识=声明['id'] if 声明 is not None and 'id' in 声明 else None#声明 id
            if 标识==根:#去掉根
                continue#跳过
            结果.append({'name':声明['name'] if 声明 is not None and 'name' in 声明 else None,'declaration':自身.渲染器.renderDeclaration(标识)})#投影
        def 按名(项):#按 name 字段排序
            """按 name 字段排序。"""
            return 项['name']#名
        结果.sort(key=按名)#按名排序
        return 结果#附属类型

    def 渲染Js(自身,包模型,模式制品,运行时):#渲染本包 JS 制品
        """生成文件头 + zod + TYPERT。"""
        行列表=['/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */']#头
        if len(模式制品['definitions'])>0:#有定义
            行列表.extend(["import { z } from 'zod'",''])#导入 zod
        行列表.extend(模式制品['definitions'])#内部定义
        if len(模式制品['definitions'])>0:#定义后空行
            行列表.append('')#空行
        for 导出 in 模式制品['exports']:#再导出各模式
            行列表.append('export const '+导出['exportName']+' = '+导出['internalName'])#导出
        if len(模式制品['exports'])>0:#导出后空行
            行列表.append('')#空行
        模型文=json.dumps(运行时,ensure_ascii=False,indent=2)#运行时快照 JSON
        行列表.append('export const TYPERT = {')#TYPERT 起
        行列表.append('  package: '+引号(包模型['name'] if 包模型 is not None and 'name' in 包模型 else None)+',')#包名
        行列表.append('  face: '+引号(自身.面['face'] if 自身.面 is not None and 'face' in 自身.面 else None)+',')#面名
        行列表.append('  schemas: [')#模式表起
        for 导出 in 模式制品['exports']:#逐条
            行列表.append('    { name: '+引号(导出['exportName'])+', create: '+导出['exportName']+' },')#名与工厂
        行列表.append('  ],')#schemas 止
        行列表.append('  invocations: [')#调用表起
        for 调用 in (包模型['invocations'] if 包模型 is not None and 'invocations' in 包模型 else None) or []:#逐条调用
            行列表.append(缩进(自身.调用字面量(调用,模式制品),4)+',')#缩进后的字面量
        行列表.append('  ],')#invocations 止
        行列表.append('  model: '+缩进(模型文,2).lstrip()+',')#嵌入快照
        行列表.append('}')#TYPERT 止
        return '\n'.join(行列表)+'\n'#源码

    def 渲染Dts(自身,包模型,模式制品):#渲染本包声明制品
        """ZodType 钉到源类型；TYPERT 对外 unknown。"""
        导入表={}#说明符 → 导入名
        包名=包模型['name'] if 包模型 is not None and 'name' in 包模型 else None#包名
        for 导出 in 模式制品['exports']:#逐条
            模型导出=导出['model']['export'] if 导出 is not None and 'model' in 导出 and 导出['model'] is not None and 'export' in 导出['model'] else None#导出示路径
            说明符=包导出说明符(包名,模型导出['subpath'] if 模型导出 is not None and 'subpath' in 模型导出 else None)#说明符
            导入表.setdefault(说明符,[]).append((模型导出['name'] if 模型导出 is not None and 'name' in 模型导出 else None)+' as '+导出['exportName']+'$source')#别名
        行列表=['/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */']#头
        if len(模式制品['exports'])>0:#有导出
            行列表.insert(1,"import type { z } from 'zod'")#导入 z
        for 说明符 in sorted(导入表):#按说明符排序
            行列表.append('import type { '+', '.join(sorted(导入表[说明符]))+' } from '+引号(说明符))#类型导入
        行列表.append('')#空行
        for 导出 in 模式制品['exports']:#逐条模式
            行列表.append('export declare const '+导出['exportName']+': () => z.ZodType<'+导出['exportName']+'$source>')#工厂类型
        if len(模式制品['exports'])>0:#声明后空行
            行列表.append('')#空行
        行列表.append('export declare const TYPERT: unknown')#对外 unknown
        return '\n'.join(行列表)+'\n'#声明

    def 输出远程(自身,包模型):#输出 Host-for-Client Remote 制品
        """只为调用边界输出模式。"""
        调用列表=(包模型['invocations'] if 包模型 is not None and 'invocations' in 包模型 else None) or []#调用
        模式制品=模式代码输出器(自身.渲染器,[],边界根列表(调用列表)).输出代码()#立刻输出
        行列表=['/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */']#头
        if len(模式制品['definitions'])>0:#有定义
            行列表.extend(["import { z } from 'zod'",''])#导入
        行列表.extend(模式制品['definitions'])#定义
        if len(模式制品['definitions'])>0:#空行
            行列表.append('')#空行
        行列表.append('export const TYPERT_REMOTE = {')#起
        行列表.append('  package: '+引号(包模型['name'] if 包模型 is not None and 'name' in 包模型 else None)+',')#包名
        行列表.append('  descriptors: [')#描述符表
        for 调用 in 调用列表:#逐条
            行列表.append(缩进(自身.调用字面量(调用,模式制品),4)+',')#字面量
        行列表.append('  ],')#止
        行列表.append('}')#对象止
        行列表.append('')#空行
        行列表.append('export default TYPERT_REMOTE')#默认导出
        声明=自身.渲染远程Dts(包模型)#声明与 map
        return {'js':'\n'.join(行列表)+'\n',**声明}#Remote 制品

    def 调用字面量(自身,调用,模式制品):#一条调用的 JS 字面量
        """拼对象字面量。"""
        行列表=['{','  id: '+引号(调用['id'] if 调用 is not None and 'id' in 调用 else None)+',','  service: '+引号(调用['service'] if 调用 is not None and 'service' in 调用 else None)+',','  namespace: '+引号(调用['namespace'] if 调用 is not None and 'namespace' in 调用 else None)+',','  method: '+引号(调用['method'] if 调用 is not None and 'method' in 调用 else None)+',']#固定字段
        实现=调用['implementation'] if 调用 is not None and 'implementation' in 调用 else None#实现名
        if 实现 is not None:#有实现名
            行列表.append('  implementation: '+引号(实现)+',')#实现
        模式=调用['mode'] if 调用 is not None and 'mode' in 调用 else None#调用模式
        if 模式 is not None:#有模式
            行列表.append('  mode: '+引号(模式)+',')#模式
        约定=(调用['invocation'] if 调用 is not None and 'invocation' in 调用 else None) or {}#调用约定
        if (约定['kind'] if 约定 is not None and 'kind' in 约定 else None)=='direct':#直接调用
            行列表.append("  invocation: { kind: 'direct' },")#直接
        else:#从 Context 解析
            行列表.append('  invocation: {')#起
            行列表.append("    kind: 'context',")#种类
            行列表.append('    context: '+引号(约定['context'] if 约定 is not None and 'context' in 约定 else None)+',')#Context 键
            行列表.append('    wire: '+引号(约定['wire'] if 约定 is not None and 'wire' in 约定 else None)+',')#身份线路
            行列表.append('    codec: '+缩进(严格编解码字面量(约定['boundary'] if 约定 is not None and 'boundary' in 约定 else None,模式制品['boundary'](上下文边界键(调用))),4).lstrip()+',')#身份编解码
            行列表.append('  },')#止
        作用域=调用['scope'] if 调用 is not None and 'scope' in 调用 else None#scope
        if 作用域 is not None:#有作用域
            行列表.append('  scope: {')#起
            行列表.append('    context: '+引号(作用域['context'] if 作用域 is not None and 'context' in 作用域 else None)+',')#键
            行列表.append('    wire: '+引号(作用域['wire'] if 作用域 is not None and 'wire' in 作用域 else None)+',')#线路
            行列表.append('  },')#止
        行列表.append('  parameters: [')#参数表
        for 序号,参数 in enumerate((调用['parameters'] if 调用 is not None and 'parameters' in 调用 else None) or []):#逐个
            行列表.append('    {')#起
            行列表.append('      name: '+引号(参数['name'] if 参数 is not None and 'name' in 参数 else None)+',')#名
            行列表.append('      wire: '+引号(参数['wire'] if 参数 is not None and 'wire' in 参数 else None)+',')#线路
            行列表.append('      source: '+引号(参数['source'] if 参数 is not None and 'source' in 参数 else None)+',')#json/lookup
            查找=参数['lookup'] if 参数 is not None and 'lookup' in 参数 else None#lookup
            if 查找 is not None:#有 lookup
                行列表.append('      lookup: '+引号(查找)+',')#lookup
            边界=参数['boundary'] if 参数 is not None and 'boundary' in 参数 else None#边界
            if 边界 is not None and 'acceptsUndefined' in 边界 and 边界['acceptsUndefined']:#显式接受 undefined
                行列表.append('      acceptsUndefined: true,')#标记
            行列表.append('      codec: '+缩进(严格编解码字面量(边界,模式制品['boundary'](参数边界键(调用,序号))),6).lstrip()+',')#编解码
            行列表.append('    },')#止
        行列表.append('  ],')#参数止
        if (调用['cancellation'] if 调用 is not None and 'cancellation' in 调用 else None) is not None:#有取消
            行列表.append("  cancellation: { parameter: 'signal' },")#signal
        行列表.append('  result: '+缩进(严格编解码字面量(调用['result'] if 调用 is not None and 'result' in 调用 else None,模式制品['boundary'](结果边界键(调用))),2).lstrip()+',')#结果
        行列表.append('  sourceLocation: '+json.dumps(调用['location'] if 调用 is not None and 'location' in 调用 else None,ensure_ascii=False)+',')#源码位置
        行列表.append('}')#对象止
        return '\n'.join(行列表)#多行字面量

    def 渲染远程Dts(自身,包模型):#渲染 Remote 声明与 map
        """模块扩充 + TYPERT_REMOTE 声明；dtsMap 为合法空映射。"""
        调用列表=(包模型['invocations'] if 包模型 is not None and 'invocations' in 包模型 else None) or []#调用
        导入列表=收集远程导入(调用列表)#公开业务类型导入
        引用名=分配远程导入名(导入列表)#本地名
        分组={}#说明符 → 导入项
        for 项 in 导入列表:#按说明符分组
            说明符=项['specifier'] if 项 is not None and 'specifier' in 项 else None#说明符
            分组.setdefault(说明符,[]).append({'name':项['name'] if 项 is not None and 'name' in 项 else None,'local':引用名[项['symbol'] if 项 is not None and 'symbol' in 项 else None]})#项
        行列表=[#声明行
            '/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */',
            'import type {',
            '  RemoteResult,',
            '  TypertRemoteContribution,',
            "} from '@deepseek-ai/dsh-typert-protocol'",
        ]#协议导入
        def 按本地名(项):#按 local 字段排序
            """按 local 字段排序。"""
            return 项['local']#本地名
        for 说明符 in sorted(分组):#按说明符
            项列表=sorted(分组[说明符],key=按本地名)#按本地名
            名列表=[项['name'] if 项['name']==项['local'] else 项['name']+' as '+项['local'] for 项 in 项列表]#渲染
            行列表.append('import type { '+', '.join(名列表)+' } from '+引号(说明符))#业务导入
        行列表.append('')#空行
        行列表.append("declare module '@deepseek-ai/dsh-typert-protocol' {")#模块扩充
        直接=[]#直接调用
        作用域调用=[]#scoped 调用
        for 调用 in 调用列表:#分流
            约定=调用['invocation'] if 调用 is not None and 'invocation' in 调用 else None#约定
            种类=约定['kind'] if 约定 is not None and 'kind' in 约定 else None#种类
            if 种类=='direct':#直接
                直接.append(调用)#记下
            if 种类=='context' or (调用['scope'] if 调用 is not None and 'scope' in 调用 else None) is not None:#scoped
                作用域调用.append(调用)#记下
        if len(直接)>0:#有直接调用
            for 命名空间 in 去重命名空间(直接):#每个命名空间
                行列表.append('  interface '+远程命名空间接口(命名空间)+' {')#接口起
                for 调用 in 直接:#该命名空间方法
                    if (调用['namespace'] if 调用 is not None and 'namespace' in 调用 else None)==命名空间:#命中
                        键=渲染远程属性名(调用['method'] if 调用 is not None and 'method' in 调用 else None)#方法名
                        行列表.append('    '+键+': '+自身.远程函数类型(调用,引用名,False))#方法签名
                行列表.append('  }')#接口止
            行列表.append('  interface TypertRemoteMap {')#扁平映射
            for 调用 in 直接:#逐条
                行列表.append('    '+自身.远程签名(调用,引用名,False))#非 scoped
            行列表.append('  }')#止
            行列表.append('  interface TypertRemoteNamespaceMap {')#命名空间映射
            for 命名空间 in 去重命名空间(直接):#逐个
                行列表.append('    '+引号(命名空间)+': '+远程命名空间接口(命名空间))#名到接口
            行列表.append('  }')#止
        if len(作用域调用)>0:#有作用域调用
            行列表.append('  interface TypertRemoteScopeMap {')#ScopeMap
            for 调用 in 作用域调用:#逐条
                行列表.append('    '+自身.远程签名(调用,引用名,True))#scoped 键
            行列表.append('  }')#止
        行列表.append('}')#模块扩充止
        行列表.append('')#空行
        行列表.append('export declare const TYPERT_REMOTE: TypertRemoteContribution')#贡献常量
        行列表.append('export default TYPERT_REMOTE')#默认导出
        行列表.append('//# sourceMappingURL=typert.remote-client.d.ts.map')#指向 map
        return {#声明制品
            'dts':'\n'.join(行列表)+'\n',#声明
            'dtsMap':json.dumps({'version':3,'file':'typert.remote-client.d.ts','sources':[],'names':[],'mappings':''},ensure_ascii=False)+'\n',#合法空映射（细粒度需 gen-mapping）
        }#结束

    def 远程签名(自身,调用,引用名,作用域键):#渲染 TypertRemoteMap / ScopeMap 的一条属性
        """键: 函数类型。"""
        约定=(调用['invocation'] if 调用 is not None and 'invocation' in 调用 else None) or {}#约定
        if (约定['kind'] if 约定 is not None and 'kind' in 约定 else None)=='context':#context 调用
            上下文=约定['context'] if 约定 is not None and 'context' in 约定 else None#身份 Context
        else:#否则用 scope
            作用域=调用['scope'] if 调用 is not None and 'scope' in 调用 else None#scope
            上下文=作用域['context'] if 作用域 is not None and 'context' in 作用域 else None#scope.context
        命名空间=调用['namespace'] if 调用 is not None and 'namespace' in 调用 else None#命名空间
        方法=调用['method'] if 调用 is not None and 'method' in 调用 else None#方法
        if 作用域键:#scoped 键
            键=str(上下文)+':'+str(命名空间)+'/'+str(方法)#context:ns/method
        else:#直接键
            键=str(命名空间)+'/'+str(方法)#ns/method
        return 引号(键)+': '+自身.远程函数类型(调用,引用名,作用域键)#引号键加函数类型

    def 远程函数类型(自身,调用,引用名,作用域键):#渲染消费方看到的 Remote 函数类型
        """(...) => Promise<RemoteResult<T>>。"""
        参数列表=[]#形参文本
        作用域=调用['scope'] if 调用 is not None and 'scope' in 调用 else None#scope
        作用域线路=作用域['wire'] if 作用域 is not None and 'wire' in 作用域 else None#scope 线路
        约定=调用['invocation'] if 调用 is not None and 'invocation' in 调用 else None#约定
        约定种类=约定['kind'] if 约定 is not None and 'kind' in 约定 else None#种类
        for 参数 in (调用['parameters'] if 调用 is not None and 'parameters' in 调用 else None) or []:#筛参数
            if 作用域键 and 约定种类!='context' and (参数['wire'] if 参数 is not None and 'wire' in 参数 else None)==作用域线路:#由键携带
                continue#省略
            可选='?' if (参数['optional'] if 参数 is not None and 'optional' in 参数 else None) is True else ''#可选
            边界=参数['boundary'] if 参数 is not None and 'boundary' in 参数 else None#边界
            参数列表.append(安全标识符(参数['wire'] if 参数 is not None and 'wire' in 参数 else None)+可选+': '+自身.渲染器.renderType(边界['type'] if 边界 is not None and 'type' in 边界 else None,引用名))#线路名作参数
        if (调用['cancellation'] if 调用 is not None and 'cancellation' in 调用 else None) is not None:#有取消
            参数列表.append('signal?: AbortSignal')#signal
        结果边界=调用['result'] if 调用 is not None and 'result' in 调用 else None#结果边界
        结果=自身.渲染器.renderType(结果边界['type'] if 结果边界 is not None and 'type' in 结果边界 else None,引用名)#结果手写类型
        if (调用['mode'] if 调用 is not None and 'mode' in 调用 else None)=='stream':#流式
            return '('+', '.join(参数列表)+') => AsyncIterable<'+结果+'>'#流
        return '('+', '.join(参数列表)+') => Promise<RemoteResult<'+结果+'>>'#包装
