"""本应用转发宿主事件白名单的唯一出处。

配置键、事件名字面量保持线协议。
"""
远程转发事件=(#宿主事件转发白名单
    'agent-preset/selected',#智能体预设已选定
    'approval/request',#审批请求瀑布
    'api-session/activity',#会话活动
    'api-session/added',#会话已添加
    'api-session/error',#会话错误
    'api-session/removed',#会话已移除
    'api-session/status',#会话状态
    'commands/change',#命令表已变更
    'credentials/reference-updated',#凭证引用已更新
    'goal/activation-changed',#目标激活已变更
    'cordis/request-run',#请求运行动态包
    'cordis/request-run-resolved',#动态包运行请求已决议
    'cordis/dynamic-package',#动态包清单
    'cordis/dynamic-retract',#动态包撤回
    'cordis/inspect-query',#动态包探查查询
    'cordis/inspect-query-resolved',#动态包探查查询已决议
    'llm/adapters-updated',#大模型适配器已更新
    'permission-presets/catalog-changed',#权限预设目录已变更
    'plugin-manager/changed',#插件装载已变更
    'plugin-manager/install-log',#插件安装日志
    'plugin-manager/install-state',#插件安装状态
    'settings/document-updated',#设置文档已更新
    'user-questions/request',#用户提问瀑布
)#只读元组，元素为字面量事件名

__all__=['远程转发事件']#公开面
