"""`conversation` 命名空间词典。

对齐上游 `ui-conversation/src/client/locales.ts`。公开面仅中文名。
"""

__all__=['命名空间','中文','英文']#仅中文公开名

命名空间='conversation'#词典命名空间名

计划下一步中文='描述你的任务以生成计划'#中文下一步动作文案
计划下一步英文='describe your task to generate plan'#英文下一步动作文案

中文={#简体中文词条
    'view.chat':'对话','hint.plan':计划下一步中文,'hint.goal':'输入目标，智能体将持续执行',
    'hint.goal.active':'当前目标进行中。可输入 edit 修改 / pause 暂停 / resume 继续 / clear 清除',
    'placeholder.plan':计划下一步中文,'placeholder.default':'发消息或创建任务, / 调用指令, @ 文件或对话',
    'placeholder.unavailable':'会话不可用',
    'placeholder.parentOffline':'父会话已离线，无法继续发送；仍可停止当前运行',
    'placeholder.hero':'描述你想要构建的内容, / 调用指令, @ 文件或对话','placeholder.workspace':'选择一个工作区开始',
    'input.commands':'添加文件或调用指令','input.file':'文件','input.stop':'停止生成','input.send':'发送消息',
    'input.send.queue':'排队发送','input.send.steer':'插话发送',
    'placeholder.steerQueue':'Cmd/Ctrl+Enter 插话发送全部排队消息',
    'input.accessMode':'访问模式，当前：{name}',
    'attachment.pending':'待发送附件','attachment.scrollLeft':'向左滚动附件','attachment.scrollRight':'向右滚动附件',
    'attachment.dropTitle':'文件或图片拖动到此处即可添加','attachment.dropDesc':'图片限制：最多 {count} 张，每张 {size}',
    'attachment.dropBlocked':'当前无法添加文件或图片',
    'image.dropTitle':'图片拖动到此处即可添加','image.dropDesc':'最多 {count} 张，每张 {size}',
    'image.dropBlocked':'当前无法添加图片','image.pending':'待发送图片',
    'image.openOriginal':'查看原图','image.openOriginalLabel':'{label}，点击查看原图',
    'image.remove':'移除图片 {name}','image.scrollLeft':'向左滚动图片','image.scrollRight':'向右滚动图片',
    'image.original':'原图','image.label':'图片','image.loadFailed':'图片加载失败，点击重试',
    'image.loading':'图片加载中…','image.preview':'原图预览','image.closePreview':'关闭原图预览',
    'image.serviceUnavailable':'图片读取服务不可用',
    'image.unsupportedType':'仅支持 PNG、JPG、WebP、GIF 格式的图片',
    'image.tooMany':'一条消息最多添加 {count} 张图片','image.fileTooLarge':'单张图片不能超过 {size}',
    'image.totalTooLarge':'图片总大小超过 {size}，请移除部分图片',
    'image.tooManyPixels':'图片分辨率过大，请压缩后重试',
    'image.dimensionTooLarge':'图片宽高不能超过 {size}px，请缩小后重试',
    'image.modelUnsupported':'当前模型不支持图片，请切换支持图片的模型',
    'image.subagentUnsupported':'子智能体会话暂不支持图片',
    'image.sendFailed':'图片发送失败（{reason}），请重新添加图片后再试',
    'file.pending':'待发送文件','file.remove':'移除文件 {name}','file.uploading':'上传中…',
    'file.uploadFailed':'上传失败，点击重试','file.retry':'重试上传 {name}',
    'file.stillUploading':'文件还在上传，请等待上传完成后发送',
    'file.sessionUnavailable':'会话不可用，无法上传文件',
    'file.notStaged':'文件尚未上传成功，请重新添加后再试','file.label':'文件',
    'context.aria':'上下文已用 {percent}','context.used':'上下文已用',
    'context.system':'系统提示词','context.tools':'工具定义','context.messages':'对话消息',
    'stats.counts':'{turns} 轮 · {steps} 步','stats.llm':'LLM {duration}',
    'stats.toolCall':'工具调用 {duration}','stats.ttftAverage':'首 token 平均 {duration}',
    'stats.tokensPerSecond':'{throughput} tok/s','stats.cacheHit':'缓存命中 {percent}%',
    'stats.tokens':'输入 {input} tok · 输出 {output} tok',
    'settings.enter.title':'繁忙时的发送行为',
    'settings.enter.description':'智能体运行时 Enter 键和发送按钮的行为；Cmd/Ctrl+Enter 使用另一行为',
    'settings.enter.queue':'排队发送','settings.enter.steer':'插话发送',
    'access.preset.readOnly':'仅可查看','access.preset.workspaceWrite':'工作区内修改','access.preset.fullAccess':'完全权限',
    'access.confirm.title':'确认启用完全权限？',
    'access.confirm.description':'启用完全权限后，智能体将减少确认步骤，并且可以直接执行更多操作，包括敏感操作、文件修改或外部命令。仅建议在你信任当前任务时使用。',
    'access.confirm.acknowledge':'我已了解风险，并愿意继续',
    'access.confirm.cancel':'取消','access.confirm.enable':'启用完全权限',
    'hero.headline':'探索未至之境','hero.preview':'预览版','hero.chooseWorkspace':'选择工作区',
    'session.hierarchy':'会话层级','details.title':'详情','details.close':'关闭详情',
    'details.empty':'点击消息流中的工具行查看详情','details.notInWindow':'该调用不在当前窗口内',
    'details.input':'输入','details.output':'输出','details.running':'运行中…',
    'todo.title':'任务','todo.progress.done':'{done} 已完成','todo.progress.active':'{active} 进行中',
    'todo.progress.pending':'{pending} 待处理','todo.rowTitle':'更新任务清单',
    'todo.completed':'{done}/{total} 已完成',
    'chat.loadingHistory':'载入历史…','chat.loadError':'历史加载失败：{message}（{code}）',
    'chat.loadOlder':'加载更早','chat.toBottom':'回到底部',
    'message.extraBlock':'附加内容块','message.contextInjection':'上下文注入',
    'message.contextRecall':'跨会话召回',
    'message.context.instructions.loaded':'已载入','message.context.instructions.added':'已新增',
    'message.context.instructions.updated':'已更新','message.context.instructions.removed':'已移除',
    'message.context.catalog.replaced':'替换目录','message.context.catalog.more':'…还有 {count} 条',
    'message.context.snapshot.supersedes':'取代先前的快照',
    'message.context.relay.from':'来自会话 {session}',
    'message.context.recall.counts':'保留 {retained} 条 · 省略 {omitted} 条',
    'message.context.recall.truncated':'已截断',
    'message.compaction':'上下文已压缩','message.compaction.running':'正在压缩…',
    'message.compaction.completed':'已压缩 {items} 条历史记录（约 {tokens} tokens）',
    'message.compaction.expand':'点击查看压缩摘要','message.compaction.unavailable':'压缩摘要不可用',
    'message.unknownSurface':'未知 surface 事件：{type}','message.unknownBlock':'未知内容块',
    'message.stopped':'已停止','message.branch':'在新对话中分支',
    'message.branchUnavailable':'仅可从已完成轮次的最后一条消息分支',
    'message.retry.active':'正在重试模型请求','message.retry.cancelled':'模型请求重试已取消',
    'message.retry.started':'已重试模型请求','message.retry.scheduled':'等待重试模型请求',
    'message.retry.status':'{label}（{retry}/{maximum}） · {seconds}s',
    'message.retry.delay':'重试延迟：','message.retry.failure':'失败原因：',
    'message.turnError':'本轮运行失败','message.maxTokens':'已达到输出 token 上限',
    'message.maxTokens.hint':'回答被截断，已有输出保留在对话中。发送“继续”可让模型接着输出。',
    'message.ranFor':'用时 {duration}','message.ttft':'首 token {seconds}秒',
    'message.tokensPerSecond':'{tps} tok/s',
    'duration.seconds':'{seconds}秒','duration.minutes':'{minutes}分{seconds}秒',
    'command.running':'执行中…','command.failed':'命令失败','command.done':'已完成','command.title':'命令',
    'command.attachmentsUnsupported':'/{command} 不接受附件，请先移除附件',
    'approval.waiting':'等待审批','approval.detail.aria':'审批详情',
    'approval.escalation':'工具 {toolName} 请求越权执行',
    'approval.reject':'拒绝','approval.allowOnce':'允许一次',
    'ask.rowTitle':'提问','ask.waiting':'等待回答','ask.cancelled':'已取消',
    'ask.cancelledDetail':'本轮已取消，未提交回答','ask.interrupted':'已中断',
    'ask.interruptedDetail':'本轮已中断，未提交回答','ask.answered':'{answered}/{total} 已回答','ask.skipped':'未回答',
    'bash.running':'运行中','bash.failed':'失败','bash.stopped':'已停止',
    'row.running':'运行中','row.failed':'失败','row.stopped':'已停止',
    'row.input':'输入','row.output':'输出','row.inspect':'查看',
    'tool.title.search':'搜索','tool.title.read':'读取','tool.title.bash':'Bash',
    'tool.title.write':'写入','tool.title.edit':'编辑','tool.title.code':'代码',
    'tool.title.generic':'工具调用','tool.title.inspect':'查看',
    'tool.title.runCordis':'运行 Cordis 插件','tool.title.stopCordis':'停止 Cordis 插件',
    'tool.title.removeCordis':'移除 Cordis 插件','tool.title.pwsh':'Pwsh',
    'tool.title.readImage':'读取图片','tool.title.grep':'Grep','tool.title.glob':'Glob',
    'tool.title.webSearch':'网页搜索','tool.title.webFetch':'网页获取',
    'diff.files.one':'{count} 个文件','diff.files.other':'{count} 个文件',
    'diff.collapseAria':'收起差异','diff.expandAria':'展开其余 {count} 行差异','diff.expandRest':'… 其余 {count} 行',
    'read.window':'显示 {shown} / {total} 行','read.collapseAria':'收起内容',
    'read.expandAria':'展开其余 {count} 行','read.expandRest':'… 其余 {count} 行',
    'search.paths':'{shown} 个路径','search.paths.truncated':'显示 {shown} / 共 {total} 个路径',
    'search.matches':'{shown} 处匹配 · {files} 个文件',
    'search.matches.truncated':'显示 {shown} / 共 {total} 处匹配 · {files} 个文件',
    'search.noResults':'无结果','search.collapseAria':'收起结果',
    'search.expandAria':'展开其余 {count} 行结果','search.expandRest':'… 其余 {count} 行',
    'web.noResults':'未找到结果','web.sourcesTruncated':'来源列表已截断','web.http':'HTTP','web.contentTruncated':'内容已截断',
    'queue.count':'{n} 条排队消息','queue.sending':'发送中…','queue.image':'排队消息图片','queue.file':'排队文件 {name}',
    'queue.edit':'编辑排队消息',
    'queue.edit.unsupported':'包含非文本内容，暂不支持编辑',
    'queue.save':'保存排队消息','queue.cancelEdit':'取消编辑','queue.remove':'删除排队消息',
    'queue.steer':'插话发送','queue.steer.unavailable':'仅运行中可插话发送',
    'queue.editFailed':'编辑失败：这条消息可能已经开始发送。',
    'queue.removeFailed':'删除失败：这条消息可能已经开始发送。',
    'queue.steerFailed':'插话发送失败，请重试。',
    'terminal.signal':'信号 {signal}','terminal.exitCode':'退出码 {code}',
    'terminal.running':'运行中','terminal.failed':'失败','terminal.done':'已完成',
    'terminal.noOutput':'无输出','terminal.collapseAria':'收起输出',
    'terminal.expandAria':'展开其余 {n} 行输出','terminal.expandRest':'… 其余 {n} 行',
    'terminal.sendInput':'（发送输入）','terminal.session':'终端 {sessionId}',
    'json.truncated':'… 已截断，共 {total} 字符',
    'clock.md':'{m}月{d}日','clock.ymd':'{y}年{m}月{d}日',
}#结束中文

英文={#英文词条（键与中文权威源一致）
    'view.chat':'Chat','hint.plan':计划下一步英文,
    'hint.goal':'describe the objective for a long-running task',
    'hint.goal.active':'goal active — edit / pause / resume / clear',
    'placeholder.plan':计划下一步英文,'placeholder.default':'Message or run a task, / commands, @ files or sessions',
    'placeholder.unavailable':'Session unavailable',
    'placeholder.parentOffline':'Parent session offline; sending is unavailable but you can still stop the run',
    'placeholder.hero':'Describe what you want to build, / commands, @ files or sessions','placeholder.workspace':'Choose a workspace to start',
    'input.commands':'Add files or run commands','input.file':'File','input.stop':'Stop generating','input.send':'Send message',
    'input.send.queue':'Queue message','input.send.steer':'Steer message',
    'placeholder.steerQueue':'Cmd/Ctrl+Enter steers all queued messages',
    'input.accessMode':'Access mode, current: {name}',
    'attachment.pending':'Pending attachments','attachment.scrollLeft':'Scroll attachments left','attachment.scrollRight':'Scroll attachments right',
    'attachment.dropTitle':'Drag files or images here to add them','attachment.dropDesc':'Image limit: up to {count} images, {size} each',
    'attachment.dropBlocked':'Files and images cannot be added right now',
    'image.dropTitle':'Drag images here to add them','image.dropDesc':'Up to {count} images, {size} each',
    'image.dropBlocked':'Images cannot be added right now','image.pending':'Pending images',
    'image.openOriginal':'View original','image.openOriginalLabel':'{label}, click to view original',
    'image.remove':'Remove image {name}','image.scrollLeft':'Scroll images left','image.scrollRight':'Scroll images right',
    'image.original':'Original image','image.label':'Image','image.loadFailed':'Image failed to load; click to retry',
    'image.loading':'Loading image…','image.preview':'Original image preview','image.closePreview':'Close original image preview',
    'image.serviceUnavailable':'Image loading service unavailable',
    'image.unsupportedType':'Only PNG, JPG, WebP, and GIF images are supported',
    'image.tooMany':'A message can include up to {count} images','image.fileTooLarge':'Each image must be smaller than {size}',
    'image.totalTooLarge':'Images exceed {size} in total; remove some and try again',
    'image.tooManyPixels':'Image resolution is too high; compress it and try again',
    'image.dimensionTooLarge':'Image sides must be at most {size}px; downscale it and try again',
    'image.modelUnsupported':'The current model does not support images; switch to a model that does',
    'image.subagentUnsupported':'Subagent sessions do not support images yet',
    'image.sendFailed':'Sending images failed ({reason}); re-add them and try again',
    'file.pending':'Pending files','file.remove':'Remove file {name}','file.uploading':'Uploading…',
    'file.uploadFailed':'Upload failed; click to retry','file.retry':'Retry uploading {name}',
    'file.stillUploading':'Files are still uploading; send after they finish',
    'file.sessionUnavailable':'Session unavailable; files cannot be uploaded',
    'file.notStaged':'The file has not finished uploading; re-add it and try again','file.label':'File',
    'context.aria':'{percent} of context used','context.used':'of context used',
    'context.system':'System prompt','context.tools':'Tool definitions','context.messages':'Messages',
    'stats.counts':'{turns} turns · {steps} steps','stats.llm':'LLM {duration}',
    'stats.toolCall':'Tool call {duration}','stats.ttftAverage':'TTFT avg {duration}',
    'stats.tokensPerSecond':'{throughput} tok/s','stats.cacheHit':'Cache hit {percent}%',
    'stats.tokens':'Input {input} tok · Output {output} tok',
    'settings.enter.title':'Send behavior while busy',
    'settings.enter.description':'What Enter and the Send button do while the agent is running; Cmd/Ctrl+Enter uses the other behavior',
    'settings.enter.queue':'Queue','settings.enter.steer':'Steer',
    'access.preset.readOnly':'Read Only','access.preset.workspaceWrite':'Workspace Write','access.preset.fullAccess':'Full access',
    'access.confirm.title':'Enable Full access?',
    'access.confirm.description':'Full access reduces confirmation steps and lets the agent perform more actions directly, including sensitive operations, file changes, or external commands. Only use it when you trust the current task.',
    'access.confirm.acknowledge':'I understand the risks and want to continue',
    'access.confirm.cancel':'Cancel','access.confirm.enable':'Enable Full access',
    'hero.headline':'Into the Unknown','hero.preview':'Preview','hero.chooseWorkspace':'Choose workspace',
    'session.hierarchy':'Session hierarchy','details.title':'Details','details.close':'Close details',
    'details.empty':'Click a tool row in the message flow to view its details','details.notInWindow':'This call is outside the current window',
    'details.input':'Input','details.output':'Output','details.running':'Running…',
    'todo.title':'To-dos','todo.progress.done':'{done} completed','todo.progress.active':'{active} in progress',
    'todo.progress.pending':'{pending} pending','todo.rowTitle':'Update to-do list',
    'todo.completed':'{done}/{total} completed',
    'chat.loadingHistory':'Loading history…','chat.loadError':'Failed to load history: {message} ({code})',
    'chat.loadOlder':'Load earlier','chat.toBottom':'Back to bottom',
    'message.extraBlock':'Extra content block','message.contextInjection':'Context injection',
    'message.contextRecall':'Session recall',
    'message.context.instructions.loaded':'loaded','message.context.instructions.added':'added',
    'message.context.instructions.updated':'updated','message.context.instructions.removed':'removed',
    'message.context.catalog.replaced':'Replacement catalog','message.context.catalog.more':'… {count} more',
    'message.context.snapshot.supersedes':'Supersedes earlier snapshots',
    'message.context.relay.from':'From session {session}',
    'message.context.recall.counts':'{retained} kept · {omitted} omitted',
    'message.context.recall.truncated':'truncated',
    'message.compaction':'Context compacted','message.compaction.running':'Compacting context…',
    'message.compaction.completed':'Compacted {items} history items (~{tokens} tokens)',
    'message.compaction.expand':'View compaction summary','message.compaction.unavailable':'Compaction summary unavailable',
    'message.unknownSurface':'Unknown surface event: {type}','message.unknownBlock':'Unknown content block',
    'message.stopped':'Stopped','message.branch':'Branch into a new conversation',
    'message.branchUnavailable':'Available only on the last message of a completed turn',
    'message.retry.active':'Retrying model request','message.retry.cancelled':'Model request retry cancelled',
    'message.retry.started':'Retried model request','message.retry.scheduled':'Waiting to retry model request',
    'message.retry.status':'{label} ({retry}/{maximum}) · {seconds}s',
    'message.retry.delay':'Retry delay: ','message.retry.failure':'Failure reason: ',
    'message.turnError':'This turn failed','message.maxTokens':'Output token limit reached',
    'message.maxTokens.hint':'The reply was cut off; earlier output is preserved in the conversation. Send "continue" to let the model resume.',
    'message.ranFor':'Ran for {duration}','message.ttft':'TTFT {seconds}s',
    'message.tokensPerSecond':'{tps} tok/s',
    'duration.seconds':'{seconds}s','duration.minutes':'{minutes}m {seconds}s',
    'command.running':'Running…','command.failed':'Command failed','command.done':'Completed','command.title':'Command',
    'command.attachmentsUnsupported':'/{command} does not accept attachments; remove them first',
    'approval.waiting':'Waiting for approval','approval.detail.aria':'Approval details',
    'approval.escalation':'Tool {toolName} requests privileged execution',
    'approval.reject':'Reject','approval.allowOnce':'Allow once',
    'ask.rowTitle':'Ask question','ask.waiting':'waiting','ask.cancelled':'cancelled',
    'ask.cancelledDetail':'This question set was cancelled before answers were submitted.','ask.interrupted':'interrupted',
    'ask.interruptedDetail':'This question set was interrupted before answers were submitted.','ask.answered':'{answered}/{total} answered','ask.skipped':'Not answered',
    'bash.running':'Running','bash.failed':'Failed','bash.stopped':'Stopped',
    'row.running':'Running','row.failed':'Failed','row.stopped':'Stopped',
    'row.input':'IN','row.output':'OUT','row.inspect':'Inspect',
    'tool.title.search':'Search','tool.title.read':'Read','tool.title.bash':'Bash',
    'tool.title.write':'Write','tool.title.edit':'Edit','tool.title.code':'Code',
    'tool.title.generic':'Tool call','tool.title.inspect':'Inspect',
    'tool.title.runCordis':'Run Cordis Plugin','tool.title.stopCordis':'Stop Cordis Plugin',
    'tool.title.removeCordis':'Remove Cordis Plugin','tool.title.pwsh':'Pwsh',
    'tool.title.readImage':'Read image','tool.title.grep':'Grep','tool.title.glob':'Glob',
    'tool.title.webSearch':'Search','tool.title.webFetch':'Fetch',
    'diff.files.one':'{count} file','diff.files.other':'{count} files',
    'diff.collapseAria':'Collapse diff','diff.expandAria':'Expand {count} more diff lines','diff.expandRest':'… {count} more lines',
    'read.window':'Showing {shown} of {total} lines','read.collapseAria':'Collapse content',
    'read.expandAria':'Expand {count} more lines','read.expandRest':'… {count} more lines',
    'search.paths':'{shown} paths','search.paths.truncated':'Showing {shown} of {total} paths',
    'search.matches':'{shown} matches · {files} files',
    'search.matches.truncated':'Showing {shown} of {total} matches · {files} files',
    'search.noResults':'No results','search.collapseAria':'Collapse results',
    'search.expandAria':'Expand {count} more result lines','search.expandRest':'… {count} more lines',
    'web.noResults':'No results found','web.sourcesTruncated':'Source list truncated','web.http':'HTTP','web.contentTruncated':'Content truncated',
    'queue.count':'{n} queued messages','queue.sending':'Sending…','queue.image':'Queued message image','queue.file':'Queued file {name}',
    'queue.edit':'Edit queued message',
    'queue.edit.unsupported':'Contains non-text content; editing is not supported yet',
    'queue.save':'Save queued message','queue.cancelEdit':'Cancel editing','queue.remove':'Remove queued message',
    'queue.steer':'Steer queued message','queue.steer.unavailable':'Steering is available only while the agent is running',
    'queue.editFailed':'Edit failed: this message may have already started sending.',
    'queue.removeFailed':'Removal failed: this message may have already started sending.',
    'queue.steerFailed':'Steering failed. Try again.',
    'terminal.signal':'signal {signal}','terminal.exitCode':'exit code {code}',
    'terminal.running':'Running','terminal.failed':'Failed','terminal.done':'Done',
    'terminal.noOutput':'No output','terminal.collapseAria':'Collapse output',
    'terminal.expandAria':'Expand the remaining {n} output lines','terminal.expandRest':'… {n} more lines',
    'terminal.sendInput':'(send input)','terminal.session':'Terminal {sessionId}',
    'json.truncated':'… truncated, {total} characters total',
    'clock.md':'{m}/{d}','clock.ymd':'{y}-{m}-{d}',
}#结束英文
