"""固定的 V3 事件词表，以及命名空间化的历史不透明事件。"""

#此历史清单不得继承当前会话事件表的增删。
已发布v3事件类型=frozenset([#已发布v3读者理解的第一方事件名
    'agent-preset/selected',
    'agent/inbox/spliced',
    'approval/asked',
    'approval/decided',
    'approval/policy',
    'assistant/attempt',
    'assistant/message',
    'command/done',
    'command/run',
    'compaction/end',
    'compaction/prune',
    'compaction/start',
    'compaction/summary',
    'deliverables/presented',
    'feedback/message-delete',
    'feedback/message-put',
    'feedback/record',
    'goal/change',
    'hook/invoked',
    'hook/result',
    'image/offload',
    'llm/retry',
    'llm/retry-started',
    'model/selection',
    'permission/preset',
    'plan/mode',
    'request/context',
    'request/header',
    'sandbox/mode',
    'schedule/change',
    'session-log-deepseek/delivery-accepted',
    'session/end-seed',
    'session/title',
    'session/title-llm-request',
    'step/end',
    'step/start',
    'subagent/catalog',
    'subagent/descriptor',
    'subagent/model-selection-policy',
    'system/message',
    'team/member',
    'team/message/delivered',
    'team/message/queued',
    'team/task',
    'todo/write',
    'tool-workflow/agent-end',
    'tool-workflow/agent-start',
    'tool-workflow/run-end',
    'tool-workflow/run-start',
    'tool/call',
    'tool/ptc-dispatch',
    'tool/ptc-dispatch-start',
    'tool/result',
    'turn/end',
    'turn/start',
    'user/message',
    'web/deepseek-search-llm-request',
    'workspace/changes',
])#已发布v3事件类型结束

def 命名空间化v3不透明事件(事件):#命名空间化v3不透明事件
    """头提升后把未知可忽略事件保持为不透明。"""
    if 事件.get('ignorable') is True and 事件['type'] not in 已发布v3事件类型:#未知可忽略
        return {**事件,'type':'plugin:'+事件['type'],'ignorable':True}#加plugin前缀
    return 事件#原样
