"""`open-in-app` 命名空间词典。

对齐上游 `ui-open-in-app/src/client/locales.ts`。公开面仅中文名；
词典键与产品名英文字面量保持上游。
"""
__all__=['命名空间','中文','英文']#仅中文公开名

命名空间='open-in-app'#本插件拥有的词典命名空间

中文={#简体中文词条（键集合的权威源）
    'open.title':'在 {app} 中打开工作目录',
    'open.tooltip':'在本地打开',
    'open.error':'打开失败',
    'menu.toggle':'选择打开方式',
    'menu.aria':'打开方式',
    'app.cursor':'Cursor',
    'app.vscode':'VS Code',
    'app.vscodeinsiders':'VS Code Insiders',
    'app.windsurf':'Windsurf',
    'app.zed':'Zed',
    'app.sublimetext':'Sublime Text',
    'app.xcode':'Xcode',
    'app.androidstudio':'Android Studio',
    'app.intellij':'IntelliJ IDEA',
    'app.pycharm':'PyCharm',
    'app.webstorm':'WebStorm',
    'app.phpstorm':'PhpStorm',
    'app.goland':'GoLand',
    'app.rider':'Rider',
    'app.rustrover':'RustRover',
    'app.fork':'Fork',
    'app.sourcetree':'Sourcetree',
    'app.github':'GitHub Desktop',
    'app.tower':'Tower',
    'app.gitkraken':'GitKraken',
    'app.smartgit':'SmartGit',
    'app.sublimemerge':'Sublime Merge',
    'app.ghostty':'Ghostty',
    'app.warp':'Warp',
    'app.iterm':'iTerm2',
    'app.kitty':'kitty',
    'app.windowsterminal':'Windows Terminal',
    'app.gitbash':'Git Bash',
    'app.gnometerminal':'GNOME Terminal',
    'app.konsole':'Konsole',
    'app.finder':'访达',
    'app.explorer':'文件资源管理器',
    'app.filemanager':'文件管理器',
    'app.terminal':'终端',
}#中文词典结束

英文={#英文词条，对照中文权威源核验键齐全
    'open.title':'Open workspace in {app}',
    'open.tooltip':'Open locally',
    'open.error':'Failed to open',
    'menu.toggle':'Choose an app to open in',
    'menu.aria':'Open in',
    'app.cursor':'Cursor',
    'app.vscode':'VS Code',
    'app.vscodeinsiders':'VS Code Insiders',
    'app.windsurf':'Windsurf',
    'app.zed':'Zed',
    'app.sublimetext':'Sublime Text',
    'app.xcode':'Xcode',
    'app.androidstudio':'Android Studio',
    'app.intellij':'IntelliJ IDEA',
    'app.pycharm':'PyCharm',
    'app.webstorm':'WebStorm',
    'app.phpstorm':'PhpStorm',
    'app.goland':'GoLand',
    'app.rider':'Rider',
    'app.rustrover':'RustRover',
    'app.fork':'Fork',
    'app.sourcetree':'Sourcetree',
    'app.github':'GitHub Desktop',
    'app.tower':'Tower',
    'app.gitkraken':'GitKraken',
    'app.smartgit':'SmartGit',
    'app.sublimemerge':'Sublime Merge',
    'app.ghostty':'Ghostty',
    'app.warp':'Warp',
    'app.iterm':'iTerm2',
    'app.kitty':'kitty',
    'app.windowsterminal':'Windows Terminal',
    'app.gitbash':'Git Bash',
    'app.gnometerminal':'GNOME Terminal',
    'app.konsole':'Konsole',
    'app.finder':'Finder',
    'app.explorer':'File Explorer',
    'app.filemanager':'Files',
    'app.terminal':'Terminal',
}#英文词典结束
